spring:
  application:
    name: smartfarm
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
